// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-08-15 14:15:57.304888793 -0700 PDT m=+0.050836839

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This document describes the lattice API.",
        "title": "Lattice API Docs",
        "termsOfService": "TBD",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "1.0"
    },
    "host": "localhost:8876",
    "basePath": "/v1",
    "paths": {
        "/systems": {
            "get": {
                "description": "List systems",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "GET /systems",
                "operationId": "list-systems",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.System"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "POST /systems",
                "operationId": "create-system",
                "parameters": [
                    {
                        "description": "Create system",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/rest.CreateSystemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.System"
                        }
                    }
                }
            }
        },
        "/systems/{systemId}/secrets": {
            "get": {
                "description": "list secrets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Lists secrets",
                "operationId": "list-secrets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Secret"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "set secret",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "set secret",
                "operationId": "set-secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create secret",
                        "name": "secretRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/rest.SetSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Secret"
                        }
                    }
                }
            }
        },
        "/systems/{systemId}/secrets/{id}": {
            "get": {
                "description": "get secret",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Get secret",
                "operationId": "get-secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Secret ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Secret"
                        }
                    }
                }
            }
        },
        "/systems/{systemId}/versions": {
            "get": {
                "description": "list teardowns",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "versions"
                ],
                "summary": "Lists system versions",
                "operationId": "list-system-versions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "systemId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.SystemVersion"
                            }
                        }
                    }
                }
            }
        },
        "/systems/{system}": {
            "get": {
                "description": "get system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "GET /systems/{system}",
                "operationId": "get-system",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.System"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "systems"
                ],
                "summary": "DELETE /systems/{system}",
                "operationId": "delete-system",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Result"
                        }
                    }
                }
            }
        },
        "/systems/{system}/builds": {
            "get": {
                "description": "list builds",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Lists builds",
                "operationId": "list-builds",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Build"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "build system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Build system",
                "operationId": "build-system",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create build",
                        "name": "buildRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/rest.BuildRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Build"
                        }
                    }
                }
            }
        },
        "/systems/{system}/builds/{id}": {
            "get": {
                "description": "get build",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Get build",
                "operationId": "get-build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Build"
                        }
                    }
                }
            }
        },
        "/systems/{system}/builds/{id}/logs": {
            "get": {
                "description": "get logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Get build logs",
                "operationId": "get-build-logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Node Path",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sidecar",
                        "name": "sidecar",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Follow",
                        "name": "follow",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Previous",
                        "name": "previous",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Timestamps",
                        "name": "timestamps",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "tail",
                        "name": "tail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Since",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Since Time",
                        "name": "sinceTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "log stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/systems/{system}/deploys": {
            "get": {
                "description": "list deploys",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deploys"
                ],
                "summary": "Lists deploys",
                "operationId": "list-deploys",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Deploy"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "build system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deploys"
                ],
                "summary": "Deploy system",
                "operationId": "deploy-system",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create deploy",
                        "name": "deployRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/rest.DeployRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Deploy"
                        }
                    }
                }
            }
        },
        "/systems/{system}/deploys/{id}": {
            "get": {
                "description": "get deploy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deploys"
                ],
                "summary": "Get deploy",
                "operationId": "get-deploy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Deploy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Deploy"
                        }
                    }
                }
            }
        },
        "/systems/{system}/jobs": {
            "get": {
                "description": "list jobs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Lists jobs",
                "operationId": "list-jobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Job"
                            }
                        }
                    }
                }
            }
        },
        "/systems/{system}/jobs/{id}": {
            "get": {
                "description": "get job",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job",
                "operationId": "get-job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Job"
                        }
                    }
                }
            }
        },
        "/systems/{system}/jobs/{id}/logs": {
            "get": {
                "description": "get job logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job logs",
                "operationId": "get-job-logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sidecar",
                        "name": "sidecar",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Follow",
                        "name": "follow",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Previous",
                        "name": "previous",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Timestamps",
                        "name": "timestamps",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "tail",
                        "name": "tail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Since",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Since Time",
                        "name": "sinceTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "log stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/systems/{system}/node-pools": {
            "get": {
                "description": "list node pools",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node-pools"
                ],
                "summary": "Lists node pools",
                "operationId": "list-node-pools",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.NodePool"
                            }
                        }
                    }
                }
            }
        },
        "/systems/{system}/node-pools/{id}": {
            "get": {
                "description": "get node pool",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "node-pools"
                ],
                "summary": "Get node pool",
                "operationId": "get-node-pool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "NodePool ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.NodePool"
                        }
                    }
                }
            }
        },
        "/systems/{system}/secrets/{id}": {
            "delete": {
                "description": "get system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Delete system",
                "operationId": "delete-system",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Secret ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Result"
                        }
                    }
                }
            }
        },
        "/systems/{system}/services": {
            "get": {
                "description": "list services",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Lists services",
                "operationId": "list-services",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Service"
                            }
                        }
                    }
                }
            }
        },
        "/systems/{system}/services/{id}": {
            "get": {
                "description": "get service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Get service",
                "operationId": "get-service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Service"
                        }
                    }
                }
            }
        },
        "/systems/{system}/services/{id}/logs": {
            "get": {
                "description": "get service logs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Get service logs",
                "operationId": "get-service-logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Instance",
                        "name": "instance",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sidecar",
                        "name": "sidecar",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Follow",
                        "name": "follow",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Previous",
                        "name": "previous",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Timestamps",
                        "name": "timestamps",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "tail",
                        "name": "tail",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Since",
                        "name": "since",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Since Time",
                        "name": "sinceTime",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "log stream",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/systems/{system}/teardowns": {
            "get": {
                "description": "list teardowns",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teardowns"
                ],
                "summary": "Lists teardowns",
                "operationId": "list-teardowns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Teardown"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "teardown system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teardowns"
                ],
                "summary": "Teardown system",
                "operationId": "teardown-system",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Teardown"
                        }
                    }
                }
            }
        },
        "/systems/{system}/teardowns/{id}": {
            "get": {
                "description": "get teardown",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teardowns"
                ],
                "summary": "Get teardown",
                "operationId": "get-teardown",
                "parameters": [
                    {
                        "type": "string",
                        "description": "System ID",
                        "name": "system",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Teardown ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.Teardown"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.BuildRequest": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "object",
                    "$ref": "#/definitions/v1.SystemVersion"
                }
            }
        },
        "rest.CreateSystemRequest": {
            "type": "object",
            "properties": {
                "definitionUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "object",
                    "$ref": "#/definitions/v1.SystemID"
                }
            }
        },
        "rest.DeployRequest": {
            "type": "object",
            "properties": {
                "buildId": {
                    "type": "object",
                    "$ref": "#/definitions/v1.BuildID"
                },
                "version": {
                    "type": "object",
                    "$ref": "#/definitions/v1.SystemVersion"
                }
            }
        },
        "rest.RunJobRequest": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "environment": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                }
            }
        },
        "rest.SetSecretRequest": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "v1.Build": {
            "type": "object",
            "properties": {
                "completionTimestamp": {
                    "description": "Completion timestamp\n",
                    "type": "string"
                },
                "id": {
                    "description": "ID\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.BuildID"
                },
                "services": {
                    "description": "Services maps service paths (e.g. /foo/bar/buzz) to the status of the build for that service in the Build.\n",
                    "type": "object"
                },
                "startTimestamp": {
                    "description": "Start timestamp\n",
                    "type": "string"
                },
                "state": {
                    "description": "State\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.BuildState"
                },
                "version": {
                    "description": "Version\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.SystemVersion"
                }
            }
        },
        "v1.BuildID": {
            "type": "object"
        },
        "v1.BuildState": {
            "type": "object"
        },
        "v1.Deploy": {
            "type": "object",
            "properties": {
                "buildId": {
                    "description": "Build ID\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.BuildID"
                },
                "id": {
                    "description": "ID\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.DeployID"
                },
                "state": {
                    "description": "State\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.DeployState"
                }
            }
        },
        "v1.DeployID": {
            "type": "object"
        },
        "v1.DeployState": {
            "type": "object"
        },
        "v1.Job": {
            "type": "object",
            "properties": {
                "completionTimestamp": {
                    "description": "CompletionTimestamp\n",
                    "type": "string"
                },
                "id": {
                    "description": "ID\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.JobID"
                },
                "path": {
                    "description": "Path\n",
                    "type": "string"
                },
                "startTimestamp": {
                    "description": "StartTimestamp\n",
                    "type": "string"
                },
                "state": {
                    "description": "State\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.JobState"
                }
            }
        },
        "v1.JobID": {
            "type": "object"
        },
        "v1.JobState": {
            "type": "object"
        },
        "v1.NodePool": {
            "type": "object",
            "properties": {
                "failure_info": {
                    "description": "FailureInfo\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.NodePoolFailureInfo"
                },
                "id": {
                    "description": "ID\n",
                    "type": "string"
                },
                "instanceType": {
                    "description": "FIXME: how to deal with epochs?\nInstanceType\n",
                    "type": "string"
                },
                "numInstances": {
                    "description": "NumInstances\n",
                    "type": "integer"
                },
                "path": {
                    "description": "Path\n",
                    "type": "string"
                },
                "state": {
                    "description": "State\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.NodePoolState"
                }
            }
        },
        "v1.NodePoolFailureInfo": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message\n",
                    "type": "string"
                },
                "time": {
                    "description": "Time\n",
                    "type": "string"
                }
            }
        },
        "v1.NodePoolState": {
            "type": "object"
        },
        "v1.Result": {
            "type": "object"
        },
        "v1.Secret": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "Name\n",
                    "type": "string"
                },
                "path": {
                    "description": "Secret service path\n",
                    "type": "string"
                },
                "value": {
                    "description": "Value\n",
                    "type": "string"
                }
            }
        },
        "v1.Service": {
            "type": "object",
            "properties": {
                "availableInstances": {
                    "description": "AvailableInstances\n",
                    "type": "integer"
                },
                "failureInfo": {
                    "description": "FailureInfo\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.ServiceFailureInfo"
                },
                "id": {
                    "description": "Service ID\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.ServiceID"
                },
                "instances": {
                    "description": "Instances\n",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "Message\n",
                    "type": "string"
                },
                "path": {
                    "description": "Service Path\n",
                    "type": "string"
                },
                "ports": {
                    "description": "Ports\n",
                    "type": "object"
                },
                "staleInstances": {
                    "description": "StaleInstances\n",
                    "type": "integer"
                },
                "state": {
                    "description": "State\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.ServiceState"
                },
                "terminatingInstances": {
                    "description": "TerminatingInstances\n",
                    "type": "integer"
                },
                "updatedInstances": {
                    "description": "UpdatedInstances\n",
                    "type": "integer"
                }
            }
        },
        "v1.ServiceFailureInfo": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message\n",
                    "type": "string"
                },
                "time": {
                    "description": "Time\n",
                    "type": "string"
                }
            }
        },
        "v1.ServiceID": {
            "type": "object"
        },
        "v1.ServiceState": {
            "type": "object"
        },
        "v1.System": {
            "type": "object",
            "properties": {
                "definitionUrl": {
                    "description": "git url for for where the definition lives in\n",
                    "type": "string"
                },
                "id": {
                    "description": "System ID\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.SystemID"
                },
                "services": {
                    "description": "map for service path and services currently running in the system\n",
                    "type": "object"
                },
                "state": {
                    "description": "State. One of \"pending\", \"failed\", \"deleting\", \"stable\", \"degraded\", \"scaling\", \"updating\"\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.SystemState"
                }
            }
        },
        "v1.SystemID": {
            "type": "object"
        },
        "v1.SystemState": {
            "type": "object"
        },
        "v1.SystemVersion": {
            "type": "object"
        },
        "v1.Teardown": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.TeardownID"
                },
                "state": {
                    "description": "State\n",
                    "type": "object",
                    "$ref": "#/definitions/v1.TeardownState"
                }
            }
        },
        "v1.TeardownID": {
            "type": "object"
        },
        "v1.TeardownState": {
            "type": "object"
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "apiKey",
            "in": "header"
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
