FORMAT: 1A

# Lattice API Docs

This document describes the lattice API.

## Group systems

### /v1/systems

#### GET /systems [GET]

List systems

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "definitionUrl": {
                    "description": "git url for for where the definition lives in\n",
                    "type": "string"
                  },
                  "id": {
                    "description": "System ID\n",
                    "type": "object"
                  },
                  "services": {
                    "description": "map for service path and services currently running in the system\n",
                    "type": "object"
                  },
                  "state": {
                    "description": "State. One of \"pending\", \"failed\", \"deleting\", \"stable\", \"degraded\", \"scaling\", \"updating\"\n",
                    "type": "object"
                  }
                }
              }
            }

#### POST /systems [POST]

Create a new system

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {
              "definitionUrl": "qui sed"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "definitionUrl": {
                  "type": "string"
                },
                "id": {
                  "type": "object"
                }
              }
            }

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "definitionUrl": {
                  "description": "git url for for where the definition lives in\n",
                  "type": "string"
                },
                "id": {
                  "description": "System ID\n",
                  "type": "object"
                },
                "services": {
                  "description": "map for service path and services currently running in the system\n",
                  "type": "object"
                },
                "state": {
                  "description": "State. One of \"pending\", \"failed\", \"deleting\", \"stable\", \"degraded\", \"scaling\", \"updating\"\n",
                  "type": "object"
                }
              }
            }

### /v1/systems/{system}

#### GET /systems/{system} [GET]

get system

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {
              "definitionUrl": "in"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "definitionUrl": {
                  "description": "git url for for where the definition lives in\n",
                  "type": "string"
                },
                "id": {
                  "description": "System ID\n",
                  "type": "object"
                },
                "services": {
                  "description": "map for service path and services currently running in the system\n",
                  "type": "object"
                },
                "state": {
                  "description": "State. One of \"pending\", \"failed\", \"deleting\", \"stable\", \"degraded\", \"scaling\", \"updating\"\n",
                  "type": "object"
                }
              }
            }

#### DELETE /systems/{system} [DELETE]

Delete system

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object"
            }

## Group secrets

### /v1/systems/{systemId}/secrets

#### Lists secrets [GET]

list secrets

+ Parameters

    + systemId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {
                "value": "incididunt dolore officia aute"
              },
              {
                "value": "reprehenderit",
                "name": "amet et no",
                "path": "enim irure"
              }
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "Name\n",
                    "type": "string"
                  },
                  "path": {
                    "description": "Secret service path\n",
                    "type": "string"
                  },
                  "value": {
                    "description": "Value\n",
                    "type": "string"
                  }
                }
              }
            }

#### set secret [POST]

set secret

+ Parameters

    + systemId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "value": {
                  "type": "string"
                }
              }
            }

+ Response 200 (application/json)

    OK

    + Body

            {
              "value": "ex dolore sit occaecat sunt"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "name": {
                  "description": "Name\n",
                  "type": "string"
                },
                "path": {
                  "description": "Secret service path\n",
                  "type": "string"
                },
                "value": {
                  "description": "Value\n",
                  "type": "string"
                }
              }
            }

### /v1/systems/{systemId}/secrets/{id}

#### Get secret [GET]

get secret

+ Parameters

    + systemId (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {
              "path": "sit pariatur labore ea veniam",
              "name": "elit laborum in amet",
              "value": "sed nisi magna ex"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "name": {
                  "description": "Name\n",
                  "type": "string"
                },
                "path": {
                  "description": "Secret service path\n",
                  "type": "string"
                },
                "value": {
                  "description": "Value\n",
                  "type": "string"
                }
              }
            }

### /v1/systems/{system}/secrets/{id}

#### Delete system [DELETE]

get system

+ Parameters

    + system (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object"
            }

## Group versions

### /v1/systems/{systemId}/versions

#### Lists system versions [GET]

list teardowns

+ Parameters

    + systemId (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {},
              {},
              {},
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object"
              }
            }

## Group builds

### /v1/systems/{system}/builds

#### Lists builds [GET]

list builds

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {},
              {
                "completionTimestamp": "nulla sint quis",
                "startTimestamp": "ut culpa officia"
              },
              {},
              {
                "startTimestamp": "irure laborum culpa in dolore",
                "completionTimestamp": "eu est ullamco dolore velit"
              }
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "completionTimestamp": {
                    "description": "Completion timestamp\n",
                    "type": "string"
                  },
                  "id": {
                    "description": "ID\n",
                    "type": "object"
                  },
                  "services": {
                    "description": "Services maps service paths (e.g. /foo/bar/buzz) to the status of the build for that service in the Build.\n",
                    "type": "object"
                  },
                  "startTimestamp": {
                    "description": "Start timestamp\n",
                    "type": "string"
                  },
                  "state": {
                    "description": "State\n",
                    "type": "object"
                  },
                  "version": {
                    "description": "Version\n",
                    "type": "object"
                  }
                }
              }
            }

#### Build system [POST]

build system

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "version": {
                  "type": "object"
                }
              }
            }

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "completionTimestamp": {
                  "description": "Completion timestamp\n",
                  "type": "string"
                },
                "id": {
                  "description": "ID\n",
                  "type": "object"
                },
                "services": {
                  "description": "Services maps service paths (e.g. /foo/bar/buzz) to the status of the build for that service in the Build.\n",
                  "type": "object"
                },
                "startTimestamp": {
                  "description": "Start timestamp\n",
                  "type": "string"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                },
                "version": {
                  "description": "Version\n",
                  "type": "object"
                }
              }
            }

### /v1/systems/{system}/builds/{id}

#### Get build [GET]

get build

+ Parameters

    + system (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "completionTimestamp": {
                  "description": "Completion timestamp\n",
                  "type": "string"
                },
                "id": {
                  "description": "ID\n",
                  "type": "object"
                },
                "services": {
                  "description": "Services maps service paths (e.g. /foo/bar/buzz) to the status of the build for that service in the Build.\n",
                  "type": "object"
                },
                "startTimestamp": {
                  "description": "Start timestamp\n",
                  "type": "string"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                },
                "version": {
                  "description": "Version\n",
                  "type": "object"
                }
              }
            }

#### Get build logs [GET /v1/systems/{system}/builds/{id}/logs]

get logs

+ Parameters

    + system (required)
    
    + id (required)
    
    + path (required)
    
    + sidecar
    
    + follow
    
    + previous
    
    + timestamps
    
    + tail
    
    + since
    
    + sinceTime

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    log stream

    + Body

            pariatur Ut incididunt sit anim

    + Schema

            {
              "type": "string"
            }

## Group deploys

### /v1/systems/{system}/deploys

#### Lists deploys [GET]

list deploys

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "buildId": {
                    "description": "Build ID\n",
                    "type": "object"
                  },
                  "id": {
                    "description": "ID\n",
                    "type": "object"
                  },
                  "state": {
                    "description": "State\n",
                    "type": "object"
                  }
                }
              }
            }

#### Deploy system [POST]

build system

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "buildId": {
                  "type": "object"
                },
                "version": {
                  "type": "object"
                }
              }
            }

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "buildId": {
                  "description": "Build ID\n",
                  "type": "object"
                },
                "id": {
                  "description": "ID\n",
                  "type": "object"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                }
              }
            }

### /v1/systems/{system}/deploys/{id}

#### Get deploy [GET]

get deploy

+ Parameters

    + system (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "buildId": {
                  "description": "Build ID\n",
                  "type": "object"
                },
                "id": {
                  "description": "ID\n",
                  "type": "object"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                }
              }
            }

## Group jobs

### /v1/systems/{system}/jobs

#### Lists jobs [GET]

list jobs

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {},
              {
                "startTimestamp": "ea",
                "completionTimestamp": "velit dolor officia esse qui"
              }
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "completionTimestamp": {
                    "description": "CompletionTimestamp\n",
                    "type": "string"
                  },
                  "id": {
                    "description": "ID\n",
                    "type": "object"
                  },
                  "path": {
                    "description": "Path\n",
                    "type": "string"
                  },
                  "startTimestamp": {
                    "description": "StartTimestamp\n",
                    "type": "string"
                  },
                  "state": {
                    "description": "State\n",
                    "type": "object"
                  }
                }
              }
            }

### /v1/systems/{system}/jobs/{id}

#### Get job [GET]

get job

+ Parameters

    + system (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {
              "completionTimestamp": "occaecat aute"
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "completionTimestamp": {
                  "description": "CompletionTimestamp\n",
                  "type": "string"
                },
                "id": {
                  "description": "ID\n",
                  "type": "object"
                },
                "path": {
                  "description": "Path\n",
                  "type": "string"
                },
                "startTimestamp": {
                  "description": "StartTimestamp\n",
                  "type": "string"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                }
              }
            }

#### Get job logs [GET /v1/systems/{system}/jobs/{id}/logs]

get job logs

+ Parameters

    + system (required)
    
    + id (required)
    
    + sidecar
    
    + follow
    
    + previous
    
    + timestamps
    
    + tail
    
    + since
    
    + sinceTime

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    log stream

    + Body

            est labore sed occaecat

    + Schema

            {
              "type": "string"
            }

## Group node-pools

### /v1/systems/{system}/node-pools

#### Lists node pools [GET]

list node pools

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {
                "instanceType": "tempor",
                "path": "dolore elit"
              },
              {
                "id": "proiden"
              }
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "failure_info": {
                    "description": "FailureInfo\n",
                    "type": "object",
                    "properties": {
                      "message": {
                        "description": "Message\n",
                        "type": "string"
                      },
                      "time": {
                        "description": "Time\n",
                        "type": "string"
                      }
                    }
                  },
                  "id": {
                    "description": "ID\n",
                    "type": "string"
                  },
                  "instanceType": {
                    "description": "FIXME: how to deal with epochs?\nInstanceType\n",
                    "type": "string"
                  },
                  "numInstances": {
                    "description": "NumInstances\n",
                    "type": "integer"
                  },
                  "path": {
                    "description": "Path\n",
                    "type": "string"
                  },
                  "state": {
                    "description": "State\n",
                    "type": "object"
                  }
                }
              }
            }

### /v1/systems/{system}/node-pools/{id}

#### Get node pool [GET]

get node pool

+ Parameters

    + system (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {
              "id": "consectetur nisi",
              "failure_info": {
                "time": "deserunt nulla"
              }
            }

    + Schema

            {
              "type": "object",
              "properties": {
                "failure_info": {
                  "description": "FailureInfo\n",
                  "type": "object",
                  "properties": {
                    "message": {
                      "description": "Message\n",
                      "type": "string"
                    },
                    "time": {
                      "description": "Time\n",
                      "type": "string"
                    }
                  }
                },
                "id": {
                  "description": "ID\n",
                  "type": "string"
                },
                "instanceType": {
                  "description": "FIXME: how to deal with epochs?\nInstanceType\n",
                  "type": "string"
                },
                "numInstances": {
                  "description": "NumInstances\n",
                  "type": "integer"
                },
                "path": {
                  "description": "Path\n",
                  "type": "string"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                }
              }
            }

## Group services

### /v1/systems/{system}/services

#### Lists services [GET]

list services

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {
                "path": "aute amet"
              },
              {
                "updatedInstances": 78520554,
                "path": "fugiat labore consequat Lorem"
              },
              {
                "terminatingInstances": -292780,
                "message": "eiusmod adipisicing do ut dolor"
              },
              {
                "instances": [
                  "et",
                  "dolore",
                  "non",
                  "aute",
                  "id quis cupidatat officia"
                ],
                "updatedInstances": 44668002
              }
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "availableInstances": {
                    "description": "AvailableInstances\n",
                    "type": "integer"
                  },
                  "failureInfo": {
                    "description": "FailureInfo\n",
                    "type": "object",
                    "properties": {
                      "message": {
                        "description": "Message\n",
                        "type": "string"
                      },
                      "time": {
                        "description": "Time\n",
                        "type": "string"
                      }
                    }
                  },
                  "id": {
                    "description": "Service ID\n",
                    "type": "object"
                  },
                  "instances": {
                    "description": "Instances\n",
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "message": {
                    "description": "Message\n",
                    "type": "string"
                  },
                  "path": {
                    "description": "Service Path\n",
                    "type": "string"
                  },
                  "ports": {
                    "description": "Ports\n",
                    "type": "object"
                  },
                  "staleInstances": {
                    "description": "StaleInstances\n",
                    "type": "integer"
                  },
                  "state": {
                    "description": "State\n",
                    "type": "object"
                  },
                  "terminatingInstances": {
                    "description": "TerminatingInstances\n",
                    "type": "integer"
                  },
                  "updatedInstances": {
                    "description": "UpdatedInstances\n",
                    "type": "integer"
                  }
                }
              }
            }

### /v1/systems/{system}/services/{id}

#### Get service [GET]

get service

+ Parameters

    + system (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "availableInstances": {
                  "description": "AvailableInstances\n",
                  "type": "integer"
                },
                "failureInfo": {
                  "description": "FailureInfo\n",
                  "type": "object",
                  "properties": {
                    "message": {
                      "description": "Message\n",
                      "type": "string"
                    },
                    "time": {
                      "description": "Time\n",
                      "type": "string"
                    }
                  }
                },
                "id": {
                  "description": "Service ID\n",
                  "type": "object"
                },
                "instances": {
                  "description": "Instances\n",
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                },
                "message": {
                  "description": "Message\n",
                  "type": "string"
                },
                "path": {
                  "description": "Service Path\n",
                  "type": "string"
                },
                "ports": {
                  "description": "Ports\n",
                  "type": "object"
                },
                "staleInstances": {
                  "description": "StaleInstances\n",
                  "type": "integer"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                },
                "terminatingInstances": {
                  "description": "TerminatingInstances\n",
                  "type": "integer"
                },
                "updatedInstances": {
                  "description": "UpdatedInstances\n",
                  "type": "integer"
                }
              }
            }

#### Get service logs [GET /v1/systems/{system}/services/{id}/logs]

get service logs

+ Parameters

    + system (required)
    
    + id (required)
    
    + instance (required)
    
    + sidecar
    
    + follow
    
    + previous
    
    + timestamps
    
    + tail
    
    + since
    
    + sinceTime

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    log stream

    + Body

            ipsum esse

    + Schema

            {
              "type": "string"
            }

## Group teardowns

### /v1/systems/{system}/teardowns

#### Lists teardowns [GET]

list teardowns

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            [
              {},
              {},
              {}
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "description": "ID\n",
                    "type": "object"
                  },
                  "state": {
                    "description": "State\n",
                    "type": "object"
                  }
                }
              }
            }

#### Teardown system [POST]

teardown system

+ Parameters

    + system (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "id": {
                  "description": "ID\n",
                  "type": "object"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                }
              }
            }

### /v1/systems/{system}/teardowns/{id}

#### Get teardown [GET]

get teardown

+ Parameters

    + system (required)
    
    + id (required)

+ Request (application/json)

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    OK

    + Body

            {}

    + Schema

            {
              "type": "object",
              "properties": {
                "id": {
                  "description": "ID\n",
                  "type": "object"
                },
                "state": {
                  "description": "State\n",
                  "type": "object"
                }
              }
            }

