// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package tree

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONRadix.
func (in *JSONRadix) DeepCopy() *JSONRadix {
	if in == nil {
		return nil
	}
	out := new(JSONRadix)
	in.DeepCopyInto(out)
	return out
}
