// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package tree

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvalidDepthError) DeepCopyInto(out *InvalidDepthError) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvalidDepthError.
func (in *InvalidDepthError) DeepCopy() *InvalidDepthError {
	if in == nil {
		return nil
	}
	out := new(InvalidDepthError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvalidPathError) DeepCopyInto(out *InvalidPathError) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvalidPathError.
func (in *InvalidPathError) DeepCopy() *InvalidPathError {
	if in == nil {
		return nil
	}
	out := new(InvalidPathError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvalidPathSubcomponentError) DeepCopyInto(out *InvalidPathSubcomponentError) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvalidPathSubcomponentError.
func (in *InvalidPathSubcomponentError) DeepCopy() *InvalidPathSubcomponentError {
	if in == nil {
		return nil
	}
	out := new(InvalidPathSubcomponentError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JSONRadix.
func (in *JSONRadix) DeepCopy() *JSONRadix {
	if in == nil {
		return nil
	}
	out := new(JSONRadix)
	in.DeepCopyInto(out)
	return out
}
