// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package resolver

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolutionTree) DeepCopyInto(out *ResolutionTree) {
	*out = *in
	if in.inner != nil {
		in, out := &in.inner, &out.inner
		*out = (*in).DeepCopy()
	}
	if in.v1 != nil {
		in, out := &in.v1, &out.v1
		*out = new(V1Tree)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolutionTree.
func (in *ResolutionTree) DeepCopy() *ResolutionTree {
	if in == nil {
		return nil
	}
	out := new(ResolutionTree)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1Tree) DeepCopyInto(out *V1Tree) {
	*out = *in
	if in.ResolutionTree != nil {
		in, out := &in.ResolutionTree, &out.ResolutionTree
		*out = new(ResolutionTree)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1Tree.
func (in *V1Tree) DeepCopy() *V1Tree {
	if in == nil {
		return nil
	}
	out := new(V1Tree)
	in.DeepCopyInto(out)
	return out
}
