package v1

import (
	"github.com/mlab-lattice/system/pkg/types"

	apiextensionsv1beta1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

const (
	ResourceSingularSystemRollout  = "systemrollout"
	ResourcePluralSystemRollout    = "systemrollouts"
	ResourceShortNameSystemRollout = "lsysr"
	ResourceScopeSystemRollout     = apiextensionsv1beta1.NamespaceScoped
)

type SystemRollout struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata"`
	Spec              SystemRolloutSpec   `json:"spec"`
	Status            SystemRolloutStatus `json:"status,omitempty"`
}

type SystemRolloutSpec struct {
	BuildName        string `json:"buildName"`
	LatticeNamespace types.LatticeNamespace
}

type SystemRolloutStatus struct {
	State   SystemRolloutState `json:"state,omitempty"`
	Message string             `json:"message,omitempty"`
}

type SystemRolloutState string

const (
	SystemRolloutStatePending    SystemRolloutState = "Pending"
	SystemRolloutStateAccepted   SystemRolloutState = "Accepted"
	SystemRolloutStateInProgress SystemRolloutState = "InProgress"
	SystemRolloutStateSucceeded  SystemRolloutState = "Succeeded"
	SystemRolloutStateFailed     SystemRolloutState = "Failed"
)

type SystemRolloutList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	Items           []SystemRollout `json:"items"`
}

// Below is taken from: https://github.com/kubernetes/apiextensions-apiserver/blob/master/examples/client-go/apis/cr/v1/zz_generated.deepcopy.go
// It's needed because runtime.Scheme.AddKnownTypes requires the type to implement runtime.interfaces.Object,
// which includes DeepCopyObject
// TODO: figure out how to autogen this

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRollout) DeepCopyInto(out *SystemRollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Example.
func (in *SystemRollout) DeepCopy() *SystemRollout {
	if in == nil {
		return nil
	}
	out := new(SystemRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemRollout) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRolloutList) DeepCopyInto(out *SystemRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleList.
func (in *SystemRolloutList) DeepCopy() *SystemRolloutList {
	if in == nil {
		return nil
	}
	out := new(SystemRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemRolloutList) DeepCopyObject() runtime.Object {
	return in.DeepCopy()
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRolloutSpec) DeepCopyInto(out *SystemRolloutSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleSpec.
func (in *SystemRolloutSpec) DeepCopy() *SystemRolloutSpec {
	if in == nil {
		return nil
	}
	out := new(SystemRolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRolloutStatus) DeepCopyInto(out *SystemRolloutStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleStatus.
func (in *SystemRolloutStatus) DeepCopy() *SystemRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(SystemRolloutStatus)
	in.DeepCopyInto(out)
	return out
}
