package v1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReferenceParameters) DeepCopyInto(out *ReferenceParameters) {
	//*out = *in
	//if in.Build != nil {
	//	in, out := &in.Build, &out.Build
	//	*out = new(ContainerBuild)
	//	(*in).DeepCopyInto(*out)
	//}
	//if in.Exec != nil {
	//	in, out := &in.Exec, &out.Exec
	//	*out = new(ContainerExec)
	//	(*in).DeepCopyInto(*out)
	//}
	//if in.Ports != nil {
	//	in, out := &in.Ports, &out.Ports
	//	*out = make(map[int32]ContainerPort, len(*in))
	//	for key, val := range *in {
	//		(*out)[key] = *val.DeepCopy()
	//	}
	//}
	//if in.HealthCheck != nil {
	//	in, out := &in.HealthCheck, &out.HealthCheck
	//	*out = new(ContainerHealthCheck)
	//	(*in).DeepCopyInto(*out)
	//}
	//if in.Resources != nil {
	//	in, out := &in.Resources, &out.Resources
	//	*out = new(ContainerResources)
	//	**out = **in
	//}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *ReferenceParameters) DeepCopy() *ReferenceParameters {
	//if in == nil {
	//	return nil
	//}
	//out := new(Container)
	//in.DeepCopyInto(out)
	//return out
	return nil
}
