// +build !ignore_autogenerated

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1

import (
	types "github.com/mlab-lattice/system/pkg/types"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

// GetGeneratedDeepCopyFuncs returns the generated funcs, since we aren't registering them.
//
// Deprecated: deepcopy registration will go away when static deepcopy is fully implemented.
func GetGeneratedDeepCopyFuncs() []conversion.GeneratedDeepCopyFunc {
	return []conversion.GeneratedDeepCopyFunc{
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ComponentBuild).DeepCopyInto(out.(*ComponentBuild))
			return nil
		}, InType: reflect.TypeOf(&ComponentBuild{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ComponentBuildFailureInfo).DeepCopyInto(out.(*ComponentBuildFailureInfo))
			return nil
		}, InType: reflect.TypeOf(&ComponentBuildFailureInfo{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ComponentBuildList).DeepCopyInto(out.(*ComponentBuildList))
			return nil
		}, InType: reflect.TypeOf(&ComponentBuildList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ComponentBuildStatus).DeepCopyInto(out.(*ComponentBuildStatus))
			return nil
		}, InType: reflect.TypeOf(&ComponentBuildStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Config).DeepCopyInto(out.(*Config))
			return nil
		}, InType: reflect.TypeOf(&Config{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigComponentBuild).DeepCopyInto(out.(*ConfigComponentBuild))
			return nil
		}, InType: reflect.TypeOf(&ConfigComponentBuild{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigComponentBuildBuilder).DeepCopyInto(out.(*ConfigComponentBuildBuilder))
			return nil
		}, InType: reflect.TypeOf(&ConfigComponentBuildBuilder{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigComponentBuildDockerArtifact).DeepCopyInto(out.(*ConfigComponentBuildDockerArtifact))
			return nil
		}, InType: reflect.TypeOf(&ConfigComponentBuildDockerArtifact{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigEnvoy).DeepCopyInto(out.(*ConfigEnvoy))
			return nil
		}, InType: reflect.TypeOf(&ConfigEnvoy{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigList).DeepCopyInto(out.(*ConfigList))
			return nil
		}, InType: reflect.TypeOf(&ConfigList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigProvider).DeepCopyInto(out.(*ConfigProvider))
			return nil
		}, InType: reflect.TypeOf(&ConfigProvider{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigProviderAWS).DeepCopyInto(out.(*ConfigProviderAWS))
			return nil
		}, InType: reflect.TypeOf(&ConfigProviderAWS{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigProviderLocal).DeepCopyInto(out.(*ConfigProviderLocal))
			return nil
		}, InType: reflect.TypeOf(&ConfigProviderLocal{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigSpec).DeepCopyInto(out.(*ConfigSpec))
			return nil
		}, InType: reflect.TypeOf(&ConfigSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigSystem).DeepCopyInto(out.(*ConfigSystem))
			return nil
		}, InType: reflect.TypeOf(&ConfigSystem{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigTerraform).DeepCopyInto(out.(*ConfigTerraform))
			return nil
		}, InType: reflect.TypeOf(&ConfigTerraform{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigTerraformBackend).DeepCopyInto(out.(*ConfigTerraformBackend))
			return nil
		}, InType: reflect.TypeOf(&ConfigTerraformBackend{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ConfigTerraformBackendS3).DeepCopyInto(out.(*ConfigTerraformBackendS3))
			return nil
		}, InType: reflect.TypeOf(&ConfigTerraformBackendS3{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Endpoint).DeepCopyInto(out.(*Endpoint))
			return nil
		}, InType: reflect.TypeOf(&Endpoint{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*EndpointList).DeepCopyInto(out.(*EndpointList))
			return nil
		}, InType: reflect.TypeOf(&EndpointList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*EndpointSpec).DeepCopyInto(out.(*EndpointSpec))
			return nil
		}, InType: reflect.TypeOf(&EndpointSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodePool).DeepCopyInto(out.(*NodePool))
			return nil
		}, InType: reflect.TypeOf(&NodePool{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodePoolList).DeepCopyInto(out.(*NodePoolList))
			return nil
		}, InType: reflect.TypeOf(&NodePoolList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodePoolSpec).DeepCopyInto(out.(*NodePoolSpec))
			return nil
		}, InType: reflect.TypeOf(&NodePoolSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*NodePoolStatus).DeepCopyInto(out.(*NodePoolStatus))
			return nil
		}, InType: reflect.TypeOf(&NodePoolStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*Service).DeepCopyInto(out.(*Service))
			return nil
		}, InType: reflect.TypeOf(&Service{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddress).DeepCopyInto(out.(*ServiceAddress))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddress{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressEndpointGroup).DeepCopyInto(out.(*ServiceAddressEndpointGroup))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressEndpointGroup{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressList).DeepCopyInto(out.(*ServiceAddressList))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPort).DeepCopyInto(out.(*ServiceAddressPort))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPort{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPortBaseHealthCheckConfig).DeepCopyInto(out.(*ServiceAddressPortBaseHealthCheckConfig))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPortBaseHealthCheckConfig{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPortEndpointGroupLoadBalanceConfig).DeepCopyInto(out.(*ServiceAddressPortEndpointGroupLoadBalanceConfig))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPortEndpointGroupLoadBalanceConfig{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPortHTTPConfig).DeepCopyInto(out.(*ServiceAddressPortHTTPConfig))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPortHTTPConfig{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPortHTTPEndpointGroupConfig).DeepCopyInto(out.(*ServiceAddressPortHTTPEndpointGroupConfig))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPortHTTPEndpointGroupConfig{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPortHTTPHealthCheckConfig).DeepCopyInto(out.(*ServiceAddressPortHTTPHealthCheckConfig))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPortHTTPHealthCheckConfig{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPortTCPConfig).DeepCopyInto(out.(*ServiceAddressPortTCPConfig))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPortTCPConfig{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressPortTCPHealthCheckConfig).DeepCopyInto(out.(*ServiceAddressPortTCPHealthCheckConfig))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressPortTCPHealthCheckConfig{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceAddressSpec).DeepCopyInto(out.(*ServiceAddressSpec))
			return nil
		}, InType: reflect.TypeOf(&ServiceAddressSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceBuild).DeepCopyInto(out.(*ServiceBuild))
			return nil
		}, InType: reflect.TypeOf(&ServiceBuild{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceBuildList).DeepCopyInto(out.(*ServiceBuildList))
			return nil
		}, InType: reflect.TypeOf(&ServiceBuildList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceBuildStatus).DeepCopyInto(out.(*ServiceBuildStatus))
			return nil
		}, InType: reflect.TypeOf(&ServiceBuildStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceList).DeepCopyInto(out.(*ServiceList))
			return nil
		}, InType: reflect.TypeOf(&ServiceList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*ServiceStatus).DeepCopyInto(out.(*ServiceStatus))
			return nil
		}, InType: reflect.TypeOf(&ServiceStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*System).DeepCopyInto(out.(*System))
			return nil
		}, InType: reflect.TypeOf(&System{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemBuild).DeepCopyInto(out.(*SystemBuild))
			return nil
		}, InType: reflect.TypeOf(&SystemBuild{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemBuildList).DeepCopyInto(out.(*SystemBuildList))
			return nil
		}, InType: reflect.TypeOf(&SystemBuildList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemBuildStatus).DeepCopyInto(out.(*SystemBuildStatus))
			return nil
		}, InType: reflect.TypeOf(&SystemBuildStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemList).DeepCopyInto(out.(*SystemList))
			return nil
		}, InType: reflect.TypeOf(&SystemList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemRollout).DeepCopyInto(out.(*SystemRollout))
			return nil
		}, InType: reflect.TypeOf(&SystemRollout{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemRolloutList).DeepCopyInto(out.(*SystemRolloutList))
			return nil
		}, InType: reflect.TypeOf(&SystemRolloutList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemRolloutStatus).DeepCopyInto(out.(*SystemRolloutStatus))
			return nil
		}, InType: reflect.TypeOf(&SystemRolloutStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemStatus).DeepCopyInto(out.(*SystemStatus))
			return nil
		}, InType: reflect.TypeOf(&SystemStatus{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemTeardown).DeepCopyInto(out.(*SystemTeardown))
			return nil
		}, InType: reflect.TypeOf(&SystemTeardown{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemTeardownList).DeepCopyInto(out.(*SystemTeardownList))
			return nil
		}, InType: reflect.TypeOf(&SystemTeardownList{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemTeardownSpec).DeepCopyInto(out.(*SystemTeardownSpec))
			return nil
		}, InType: reflect.TypeOf(&SystemTeardownSpec{})},
		{Fn: func(in interface{}, out interface{}, c *conversion.Cloner) error {
			in.(*SystemTeardownStatus).DeepCopyInto(out.(*SystemTeardownStatus))
			return nil
		}, InType: reflect.TypeOf(&SystemTeardownStatus{})},
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentBuild) DeepCopyInto(out *ComponentBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentBuild.
func (in *ComponentBuild) DeepCopy() *ComponentBuild {
	if in == nil {
		return nil
	}
	out := new(ComponentBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComponentBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentBuildFailureInfo) DeepCopyInto(out *ComponentBuildFailureInfo) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentBuildFailureInfo.
func (in *ComponentBuildFailureInfo) DeepCopy() *ComponentBuildFailureInfo {
	if in == nil {
		return nil
	}
	out := new(ComponentBuildFailureInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentBuildList) DeepCopyInto(out *ComponentBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComponentBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentBuildList.
func (in *ComponentBuildList) DeepCopy() *ComponentBuildList {
	if in == nil {
		return nil
	}
	out := new(ComponentBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComponentBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentBuildStatus) DeepCopyInto(out *ComponentBuildStatus) {
	*out = *in
	if in.LastObservedPhase != nil {
		in, out := &in.LastObservedPhase, &out.LastObservedPhase
		if *in == nil {
			*out = nil
		} else {
			*out = new(types.ComponentBuildPhase)
			**out = **in
		}
	}
	if in.FailureInfo != nil {
		in, out := &in.FailureInfo, &out.FailureInfo
		if *in == nil {
			*out = nil
		} else {
			*out = new(ComponentBuildFailureInfo)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentBuildStatus.
func (in *ComponentBuildStatus) DeepCopy() *ComponentBuildStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigComponentBuild) DeepCopyInto(out *ConfigComponentBuild) {
	*out = *in
	out.Builder = in.Builder
	out.DockerArtifact = in.DockerArtifact
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigComponentBuild.
func (in *ConfigComponentBuild) DeepCopy() *ConfigComponentBuild {
	if in == nil {
		return nil
	}
	out := new(ConfigComponentBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigComponentBuildBuilder) DeepCopyInto(out *ConfigComponentBuildBuilder) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigComponentBuildBuilder.
func (in *ConfigComponentBuildBuilder) DeepCopy() *ConfigComponentBuildBuilder {
	if in == nil {
		return nil
	}
	out := new(ConfigComponentBuildBuilder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigComponentBuildDockerArtifact) DeepCopyInto(out *ConfigComponentBuildDockerArtifact) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigComponentBuildDockerArtifact.
func (in *ConfigComponentBuildDockerArtifact) DeepCopy() *ConfigComponentBuildDockerArtifact {
	if in == nil {
		return nil
	}
	out := new(ConfigComponentBuildDockerArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigEnvoy) DeepCopyInto(out *ConfigEnvoy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigEnvoy.
func (in *ConfigEnvoy) DeepCopy() *ConfigEnvoy {
	if in == nil {
		return nil
	}
	out := new(ConfigEnvoy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigList) DeepCopyInto(out *ConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Config, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigList.
func (in *ConfigList) DeepCopy() *ConfigList {
	if in == nil {
		return nil
	}
	out := new(ConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProvider) DeepCopyInto(out *ConfigProvider) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		if *in == nil {
			*out = nil
		} else {
			*out = new(ConfigProviderLocal)
			**out = **in
		}
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		if *in == nil {
			*out = nil
		} else {
			*out = new(ConfigProviderAWS)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProvider.
func (in *ConfigProvider) DeepCopy() *ConfigProvider {
	if in == nil {
		return nil
	}
	out := new(ConfigProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProviderAWS) DeepCopyInto(out *ConfigProviderAWS) {
	*out = *in
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProviderAWS.
func (in *ConfigProviderAWS) DeepCopy() *ConfigProviderAWS {
	if in == nil {
		return nil
	}
	out := new(ConfigProviderAWS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigProviderLocal) DeepCopyInto(out *ConfigProviderLocal) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigProviderLocal.
func (in *ConfigProviderLocal) DeepCopy() *ConfigProviderLocal {
	if in == nil {
		return nil
	}
	out := new(ConfigProviderLocal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	out.ComponentBuild = in.ComponentBuild
	out.Envoy = in.Envoy
	if in.SystemConfigs != nil {
		in, out := &in.SystemConfigs, &out.SystemConfigs
		*out = make(map[types.LatticeNamespace]ConfigSystem, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Terraform != nil {
		in, out := &in.Terraform, &out.Terraform
		if *in == nil {
			*out = nil
		} else {
			*out = new(ConfigTerraform)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSystem) DeepCopyInto(out *ConfigSystem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSystem.
func (in *ConfigSystem) DeepCopy() *ConfigSystem {
	if in == nil {
		return nil
	}
	out := new(ConfigSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigTerraform) DeepCopyInto(out *ConfigTerraform) {
	*out = *in
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		if *in == nil {
			*out = nil
		} else {
			*out = new(ConfigTerraformBackend)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigTerraform.
func (in *ConfigTerraform) DeepCopy() *ConfigTerraform {
	if in == nil {
		return nil
	}
	out := new(ConfigTerraform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigTerraformBackend) DeepCopyInto(out *ConfigTerraformBackend) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		if *in == nil {
			*out = nil
		} else {
			*out = new(ConfigTerraformBackendS3)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigTerraformBackend.
func (in *ConfigTerraformBackend) DeepCopy() *ConfigTerraformBackend {
	if in == nil {
		return nil
	}
	out := new(ConfigTerraformBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigTerraformBackendS3) DeepCopyInto(out *ConfigTerraformBackendS3) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigTerraformBackendS3.
func (in *ConfigTerraformBackendS3) DeepCopy() *ConfigTerraformBackendS3 {
	if in == nil {
		return nil
	}
	out := new(ConfigTerraformBackendS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Endpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointList) DeepCopyInto(out *EndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemTeardown, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointList.
func (in *EndpointList) DeepCopy() *EndpointList {
	if in == nil {
		return nil
	}
	out := new(EndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	if in.ExternalEndpoint != nil {
		in, out := &in.ExternalEndpoint, &out.ExternalEndpoint
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePool) DeepCopyInto(out *NodePool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePool.
func (in *NodePool) DeepCopy() *NodePool {
	if in == nil {
		return nil
	}
	out := new(NodePool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolList) DeepCopyInto(out *NodePoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemTeardown, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolList.
func (in *NodePoolList) DeepCopy() *NodePoolList {
	if in == nil {
		return nil
	}
	out := new(NodePoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodePoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolSpec) DeepCopyInto(out *NodePoolSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolSpec.
func (in *NodePoolSpec) DeepCopy() *NodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolStatus) DeepCopyInto(out *NodePoolStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolStatus.
func (in *NodePoolStatus) DeepCopy() *NodePoolStatus {
	if in == nil {
		return nil
	}
	out := new(NodePoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Service) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddress) DeepCopyInto(out *ServiceAddress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddress.
func (in *ServiceAddress) DeepCopy() *ServiceAddress {
	if in == nil {
		return nil
	}
	out := new(ServiceAddress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAddress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressEndpointGroup) DeepCopyInto(out *ServiceAddressEndpointGroup) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoadBalance != nil {
		in, out := &in.LoadBalance, &out.LoadBalance
		if *in == nil {
			*out = nil
		} else {
			*out = new(ServiceAddressPortEndpointGroupLoadBalanceConfig)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressEndpointGroup.
func (in *ServiceAddressEndpointGroup) DeepCopy() *ServiceAddressEndpointGroup {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressEndpointGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressList) DeepCopyInto(out *ServiceAddressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemTeardown, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressList.
func (in *ServiceAddressList) DeepCopy() *ServiceAddressList {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAddressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPort) DeepCopyInto(out *ServiceAddressPort) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		if *in == nil {
			*out = nil
		} else {
			*out = new(ServiceAddressPortHTTPConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	if in.TCP != nil {
		in, out := &in.TCP, &out.TCP
		if *in == nil {
			*out = nil
		} else {
			*out = new(ServiceAddressPortTCPConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPort.
func (in *ServiceAddressPort) DeepCopy() *ServiceAddressPort {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPortBaseHealthCheckConfig) DeepCopyInto(out *ServiceAddressPortBaseHealthCheckConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPortBaseHealthCheckConfig.
func (in *ServiceAddressPortBaseHealthCheckConfig) DeepCopy() *ServiceAddressPortBaseHealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPortBaseHealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPortEndpointGroupLoadBalanceConfig) DeepCopyInto(out *ServiceAddressPortEndpointGroupLoadBalanceConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPortEndpointGroupLoadBalanceConfig.
func (in *ServiceAddressPortEndpointGroupLoadBalanceConfig) DeepCopy() *ServiceAddressPortEndpointGroupLoadBalanceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPortEndpointGroupLoadBalanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPortHTTPConfig) DeepCopyInto(out *ServiceAddressPortHTTPConfig) {
	*out = *in
	if in.EndpointGroups != nil {
		in, out := &in.EndpointGroups, &out.EndpointGroups
		*out = make(map[string]ServiceAddressPortHTTPEndpointGroupConfig, len(*in))
		for key, val := range *in {
			newVal := new(ServiceAddressPortHTTPEndpointGroupConfig)
			val.DeepCopyInto(newVal)
			(*out)[key] = *newVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPortHTTPConfig.
func (in *ServiceAddressPortHTTPConfig) DeepCopy() *ServiceAddressPortHTTPConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPortHTTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPortHTTPEndpointGroupConfig) DeepCopyInto(out *ServiceAddressPortHTTPEndpointGroupConfig) {
	*out = *in
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		if *in == nil {
			*out = nil
		} else {
			*out = new(ServiceAddressPortHTTPHealthCheckConfig)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPortHTTPEndpointGroupConfig.
func (in *ServiceAddressPortHTTPEndpointGroupConfig) DeepCopy() *ServiceAddressPortHTTPEndpointGroupConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPortHTTPEndpointGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPortHTTPHealthCheckConfig) DeepCopyInto(out *ServiceAddressPortHTTPHealthCheckConfig) {
	*out = *in
	out.ServiceAddressPortBaseHealthCheckConfig = in.ServiceAddressPortBaseHealthCheckConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPortHTTPHealthCheckConfig.
func (in *ServiceAddressPortHTTPHealthCheckConfig) DeepCopy() *ServiceAddressPortHTTPHealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPortHTTPHealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPortTCPConfig) DeepCopyInto(out *ServiceAddressPortTCPConfig) {
	*out = *in
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		if *in == nil {
			*out = nil
		} else {
			*out = new(ServiceAddressPortTCPHealthCheckConfig)
			(*in).DeepCopyInto(*out)
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPortTCPConfig.
func (in *ServiceAddressPortTCPConfig) DeepCopy() *ServiceAddressPortTCPConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPortTCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressPortTCPHealthCheckConfig) DeepCopyInto(out *ServiceAddressPortTCPHealthCheckConfig) {
	*out = *in
	out.ServiceAddressPortBaseHealthCheckConfig = in.ServiceAddressPortBaseHealthCheckConfig
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	if in.ExpectedResponse != nil {
		in, out := &in.ExpectedResponse, &out.ExpectedResponse
		if *in == nil {
			*out = nil
		} else {
			*out = new(string)
			**out = **in
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressPortTCPHealthCheckConfig.
func (in *ServiceAddressPortTCPHealthCheckConfig) DeepCopy() *ServiceAddressPortTCPHealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressPortTCPHealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAddressSpec) DeepCopyInto(out *ServiceAddressSpec) {
	*out = *in
	if in.EndpointGroups != nil {
		in, out := &in.EndpointGroups, &out.EndpointGroups
		*out = make(map[string]ServiceAddressEndpointGroup, len(*in))
		for key, val := range *in {
			newVal := new(ServiceAddressEndpointGroup)
			val.DeepCopyInto(newVal)
			(*out)[key] = *newVal
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make(map[string]ServiceAddressPort, len(*in))
		for key, val := range *in {
			newVal := new(ServiceAddressPort)
			val.DeepCopyInto(newVal)
			(*out)[key] = *newVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAddressSpec.
func (in *ServiceAddressSpec) DeepCopy() *ServiceAddressSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAddressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBuild) DeepCopyInto(out *ServiceBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBuild.
func (in *ServiceBuild) DeepCopy() *ServiceBuild {
	if in == nil {
		return nil
	}
	out := new(ServiceBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBuildList) DeepCopyInto(out *ServiceBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBuildList.
func (in *ServiceBuildList) DeepCopy() *ServiceBuildList {
	if in == nil {
		return nil
	}
	out := new(ServiceBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceBuildStatus) DeepCopyInto(out *ServiceBuildStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceBuildStatus.
func (in *ServiceBuildStatus) DeepCopy() *ServiceBuildStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceList) DeepCopyInto(out *ServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Service, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceList.
func (in *ServiceList) DeepCopy() *ServiceList {
	if in == nil {
		return nil
	}
	out := new(ServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *System) DeepCopyInto(out *System) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new System.
func (in *System) DeepCopy() *System {
	if in == nil {
		return nil
	}
	out := new(System)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *System) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemBuild) DeepCopyInto(out *SystemBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemBuild.
func (in *SystemBuild) DeepCopy() *SystemBuild {
	if in == nil {
		return nil
	}
	out := new(SystemBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemBuildList) DeepCopyInto(out *SystemBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemBuildList.
func (in *SystemBuildList) DeepCopy() *SystemBuildList {
	if in == nil {
		return nil
	}
	out := new(SystemBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemBuildStatus) DeepCopyInto(out *SystemBuildStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemBuildStatus.
func (in *SystemBuildStatus) DeepCopy() *SystemBuildStatus {
	if in == nil {
		return nil
	}
	out := new(SystemBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemList) DeepCopyInto(out *SystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]System, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemList.
func (in *SystemList) DeepCopy() *SystemList {
	if in == nil {
		return nil
	}
	out := new(SystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRollout) DeepCopyInto(out *SystemRollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemRollout.
func (in *SystemRollout) DeepCopy() *SystemRollout {
	if in == nil {
		return nil
	}
	out := new(SystemRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemRollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRolloutList) DeepCopyInto(out *SystemRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemRolloutList.
func (in *SystemRolloutList) DeepCopy() *SystemRolloutList {
	if in == nil {
		return nil
	}
	out := new(SystemRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemRolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemRolloutStatus) DeepCopyInto(out *SystemRolloutStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemRolloutStatus.
func (in *SystemRolloutStatus) DeepCopy() *SystemRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(SystemRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemStatus) DeepCopyInto(out *SystemStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemStatus.
func (in *SystemStatus) DeepCopy() *SystemStatus {
	if in == nil {
		return nil
	}
	out := new(SystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTeardown) DeepCopyInto(out *SystemTeardown) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTeardown.
func (in *SystemTeardown) DeepCopy() *SystemTeardown {
	if in == nil {
		return nil
	}
	out := new(SystemTeardown)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemTeardown) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTeardownList) DeepCopyInto(out *SystemTeardownList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SystemTeardown, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTeardownList.
func (in *SystemTeardownList) DeepCopy() *SystemTeardownList {
	if in == nil {
		return nil
	}
	out := new(SystemTeardownList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemTeardownList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	} else {
		return nil
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTeardownSpec) DeepCopyInto(out *SystemTeardownSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTeardownSpec.
func (in *SystemTeardownSpec) DeepCopy() *SystemTeardownSpec {
	if in == nil {
		return nil
	}
	out := new(SystemTeardownSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemTeardownStatus) DeepCopyInto(out *SystemTeardownStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemTeardownStatus.
func (in *SystemTeardownStatus) DeepCopy() *SystemTeardownStatus {
	if in == nil {
		return nil
	}
	out := new(SystemTeardownStatus)
	in.DeepCopyInto(out)
	return out
}
